### ISSUE TITLE
docker-compose.yml is empty

### ISSUE THREAD

**Issue by JEduardoGD** [mortegac/DockerizandoNodeMongodb#1]
docker-compose.yml dont contains any line or information

**Comment by jojo5716** [comment]
```
version: "2"


services:
    db:
        image: mongo
        expose:
            - "27017"
        volumes: 
            - mongodata:/data/db
    web:
        build: .
        depends_on:
            - db
        ports:
            - "3000:3000"
        volumes: 
            - .:/opt/app
            - /opt/app/node_modules
volumes: 
    mongodata:
```
`

Here is the docker-compose-yml (Was missing the version:"2" attribute on the tutorial https://medium.com/devschile/dockerizando-nodejs-y-mongodb-ad24fedab8f2)

Regards
